NUM_STATES=25
NUM_ACTIONS=4
DELTA = 0.001
action_str = ['UP', "DOWN", "LEFT", "RIGHT"]
action_img = ['↑', '↓', '←', '→']
OBSTACLE_STATES = [12,17]
GAMMA = 0.9
WATER_STATES = [22]
REWARD_STATES = [24]
TERMINAL_STATES = REWARD_STATES

UP = 0 
DOWN = 1
LEFT = 2
RIGHT = 3